#!/usr/bin/env bash

#============================================|
#	Downloads youtube audio
#	created by: Jean0t
#	github: github.com/jean0t
#	version: 1.2
#============================================|
#	Changelog
#
#	1.0:
#		- Downloads and extracts audios
#		  from youtube videos
#
#	1.1:
#		- Test if there are links
#		  to download
#
#	1.2:
#		- Test if the link passed is
#		  a valid youtube link
#============================================|
# INFORMATION ABOUT THE SOFTWARE

version='1.2'
[[ "$1" = "-v" || "$1" == "--version" ]] && { echo -e "Version \E[1;34m${version}\E[0m" ; exit 0 ; }

#============================================|
# VERIFICATIONS

# Do not allow root to run
[[ "$UID" -eq '0' ]] && { echo 'Do not run as root' ; exit 1 ; }

# test if the necessary module exist
[[ $( type -p yt-dlp ) ]] || { echo 'yt-dlp not found.' ; exit 1 ; }

# Test internet conection
[[ $( ping -c1 8.8.8.8 ) ]] || { echo 'You need internet conection to run the script' ; exit 1 ; }

# test if the directory exists
[[ ! -e "$HOME/Downloads/Youtube_Download" ]] \
&& { echo 'created directory ~Downloads/Youtube_Download' ; mkdir -p "$HOME/Downloads/Youtube_Download" ; }

# test if there are parameters
[[ $# -eq 0 ]] && { echo 'you need to pass an youtube link to download' ; exit 1 ; }

# test if the link is valid
youtube_regex='^(https?\:\/\/)?(www\.youtube\.com|youtu\.?be)\/.+$'
[[ $1 =~ $youtube_regex ]] || { echo 'It is not a valid link, please provide a https://youtube.com/...' ; exit 1 ; }

#============================================|
# GLOBAL VARIABLES
output_directory="$HOME/Downloads/Youtube_Download/%(title)s.%(ext)s"
#============================================|

#	START THE PROGRAM

echo 'Starting the download...'
if [[ $( yt-dlp -x -f bestaudio -o "$output_directory" --embed-thumbnail "$@" >&- 2>&- ) ]]; then
	echo 'Download was successful, saved in:'
	echo "$HOME/Downloads/Youtube_Download"
	exit 0
else
	echo $'\E[31;1mAn error has occurred\E[0m'
	exit 1
fi
