[font]
normal = { family = "FiraCode Nerd Font", style = "Regular" }
bold = { family = "FiraCode Nerd Font", style = "Bold" }
italic = { family = "FiraCode Nerd Font", style = "Italic" }
size = 12.0

[colors.primary]
foreground = "#00FF00"
background = "#000000"

[window]
title = "jean0t terminal"
dynamic_title = true
decorations = "Transparent"
opacity = 0.8
